### ISSUE TITLE
StackOverflowException on compilation of huge `...WhereInput` classes

### ISSUE THREAD

**Issue by ckittl** [coverified/graphQLConnector#2]
If data objects get a fair amount of attributes, the amount of attributes of the `...WhereInput` classes explode. (E.g., `EntryWhereInput` with the latest scheme has around 130 attributes :exploding_head:). At least for me, it lead to an overflowing stack...

AFAIK one solution would be to break down the monolitic case classes into smaller ones grouped by a sealed trait.

**Comment by ckittl** [comment]
I made a proposal for the final outcome in above mentioned PR. Routine to auto-generate it that style needs to be developed.

**Comment by johanneshiry** [comment]
May you point out why this is actually an issue? I worked with these attribute sizes for some time now and I don't see the issue here because all values are filled with default ones ... ?! Hence you could only take what you actually want and just ignore the rest of it?

**Comment by johanneshiry** [comment]
Closing this one as not valid after adapting jvm args again.
May be opened again when it happens again.
